# Generated by Django 4.2.4 on 2023-08-18 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='заголовок')),
                ('content', models.TextField(verbose_name='содержимое')),
                ('image', models.ImageField(blank=True, null=True, upload_to='material', verbose_name='изображение')),
                ('slug', models.CharField(max_length=100, verbose_name='slug')),
                ('publishing_flag', models.BooleanField(default=False, verbose_name='признак публикации')),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='дата создания')),
                ('number_of_views', models.IntegerField(verbose_name='количество просмотров')),
            ],
            options={
                'verbose_name': 'материал',
                'verbose_name_plural': 'материалы',
            },
        ),
    ]
