# Generated by Django 4.2.4 on 2023-08-20 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='number_of_views',
            field=models.IntegerField(default=0, verbose_name='количество просмотров'),
        ),
        migrations.AlterField(
            model_name='material',
            name='publishing_flag',
            field=models.BooleanField(default=True, verbose_name='признак публикации'),
        ),
        migrations.AlterField(
            model_name='material',
            name='slug',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='slug'),
        ),
    ]
