# Generated by Django 4.2.4 on 2023-09-02 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='name',
            field=models.CharField(db_column='name', max_length=100, verbose_name='название версии'),
        ),
        migrations.RenameField(
            model_name='version',
            old_name='name',
            new_name='label',
        ),
    ]
